version: '3.8'
services:
  time_complexity_service:
    build:
      context: ./time_complexity_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always

  recurrence_relation_service:
    build:
      context: ./recurrence_relation_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: always

  result_presentation_service:
    build:
      context: ./result_presentation_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    restart: always
    depends_on:
      - time_complexity_service
      - recurrence_relation_service
